# Based on https://github.com/just-the-docs/just-the-docs/blob/13a1ac2a42e666227e3145e80f030b574f5d496d/_config.yml
title: "Github Pages Site"
description: "Using Jekyll with Just-the-Docs theme"
logo: "/assets/images/logo.png"

# Start Unique to the Local Configuration Settings
# Theme
theme: "just-the-docs"
# use 
#remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
baseurl: ""
url: ""
host: 0.0.0.0

# End Unique Settings for Local

color_scheme: dark # or light

callouts_level: loud # or quiet
callouts:
  highlight: 
    title: 🌈 Highlight
    color: yellow
  important:
    title: ⚡ Important
    color: blue
  new:
    title: ✨ New  ✨
    color: pink
  note:
    title: 📝 Note
    color: purple
  warning:
    title: ⚠️ Warning
    color: red

# Aux links for the upper right navigation
aux_links:
  "Twitter": 
    - "//twitter.com/rayraspberry1"
  "Github":
    - "//github.com/rayraspberry/docker-jekyll-ghpages/"

aux_links_new_tab: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
#back_to_top: true
#back_to_top_text: "Back to top"

footer_content: ""

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
#last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit in Github"
gh_edit_repository: "https://github.com/rayraspberry/docker-jekyll-ghpages" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

# Define Jekyll collections
#collections_dir: "/"
#collections:
#  posts:
#    permalink: "/:collection/:path/"
#    output: true
  
#just_the_docs:
  # Define which collections are used in just-the-docs
#  posts:
#    contribute:
#      name: 🤝 Posts
#      nav_exclude: false
#      nav_fold: true
#      search_exclude: false

plugins:
  - jekyll-default-layout
  - jekyll-feed